www-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://metamask.io"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "www.metamask.io"
    LETSENCRYPT_HOST: "www.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

blog-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://medium.com/metamask"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "blog.metamask.io"
    LETSENCRYPT_HOST: "blog.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

support-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://metamask.zendesk.com/hc/en-us"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "support.metamask.io"
    LETSENCRYPT_HOST: "support.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
