nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ../../../volumes/proxy/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  restart: always
  volumes_from:
    - nginx-proxy
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "../../../volumes/proxy/certs:/etc/nginx/certs:rw"

www-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://metamask.io"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "www.metamask.io"
    LETSENCRYPT_HOST: "www.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

blog-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://medium.com/metamask"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "blog.metamask.io"
    LETSENCRYPT_HOST: "blog.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

support-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://metamask.zendesk.com/hc/en-us"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "support.metamask.io"
    LETSENCRYPT_HOST: "support.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

swag-redirector:
  build: redirector/
  restart: always
  ports:
    - "9000"
  environment:
    PORT: 9000
    REDIRECT_TARGET: "https://shop.spreadshirt.com/metamask"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "swag.metamask.io"
    LETSENCRYPT_HOST: "swag.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
